/**
 * Type definitions for RAW sample data (before normalization)
 *
 * Generated by quicktype from actual JSON data.
 * The transform function normalizes this messy data into clean Item types.
 */

/**
 * Complete sample data export structure
 */
export interface SampleData {
  meta: Meta
  records: SampleRecord[]
}

export interface Meta {
  source: string
  exportedAt: string
}

/**
 * Individual record from the sample data
 *
 * This represents the messy, inconsistent real-world data.
 * Note the union types for creator, date, materials - that's what we normalize!
 */
export interface SampleRecord {
  object_id: string
  accession_number: null | string
  title: null | string
  creator: SampleCreator
  date: SampleDate
  object_type: string
  department: string
  materials: SampleMaterials
  dimensions: Dimensions | null
  tags?: string[] | null
  credit_line?: string
  notes?: string[] | null
  provenance?: any[]
  external_ids?: ExternalIDS
  description?: string
  flags?: Flags
  condition?: string
  keywords?: string[]
  related?: Related[]
  geo?: Geo
  inventory_location?: number
  rights?: RightsClass | string
  transcription?: null | string
  series?: Series
  location?: Location
  variants?: Variant[]
  edition?: Edition
  status?: string
}

/**
 * Raw creator field - highly inconsistent!
 * - string[] (most common: ["Charles Eames", "Ray Eames"])
 * - string (some records: "Charles and Ray Eames")
 * - null (missing data)
 */
export type SampleCreator = string[] | null | string

/**
 * Raw date field - 4 different formats!
 * - DateClass object with display/earliest/latest
 * - number (year as number)
 * - string (various formats like "1954", "c. 1938", "1950-01-01")
 * - null (missing)
 */
export type SampleDate = DateClass | number | null | string

export interface DateClass {
  display: string
  earliest: number | null
  latest: number | null
}

/**
 * Raw materials - inconsistent like creator
 * - string[] (most common)
 * - string (some records)
 * - null (missing)
 */
export type SampleMaterials = string[] | null | string

/**
 * Dimensions - very complex and inconsistent!
 * Can have any combination of display, h, w, d, l, diameter, wingspan, unit
 */
export interface Dimensions {
  display?: null | string
  h?: DimensionValue | number | null | string
  w?: DimensionValue | number | null | string
  d?: DimensionValue | null | string
  diameter?: number | string
  l?: DimensionValue
  unit?: string
  wingspan?: string
}

export interface DimensionValue {
  value: number
  unit: string
}

export interface Edition {
  number: null
  notes: string
}

export interface ExternalIDS {
  emuseum?: null | string
  museumplus?: null | string
  imdb?: null
  internal_slug?: string
}

/**
 * All possible flags in the data
 * Our transform and display must handle all 7!
 */
export interface Flags {
  attribution_uncertain?: boolean
  prototype?: boolean
  possible_duplicate?: boolean
  materials_incomplete?: boolean
  needs_review?: boolean
  missing_dimensions?: boolean
  needs_research?: boolean
  [key: string]: boolean | undefined
}

export interface Geo {
  country: string
  region: null
}

export interface Location {
  site: string
  shelf: string
}

export interface Related {
  type: string
  object_id?: string
  slug?: string
}

export interface RightsClass {
  status: string
  notes: string
}

export interface Series {
  title: string
  type: string
}

export interface Variant {
  color?: string
  shell?: string
  finish?: string
  upholstery?: null | string
  notes?: null
}
